### ISSUE TITLE
Issues with ReactJs and create-wasm-app

### ISSUE THREAD

**Issue by DavidGOrtega** [tantaraio/voy#57]
👋 

I have tried to use Voy for a quick test and was not successful.

create-wasm-app wait hangs loading the wasm. To reproduce

```sh
yarn install
yarn dev
```

in reactjs 18 the module seems not to be there. I have tried to await the module init.

```js
const { Voy: VoyClient } = await import("voy-search");
const voyClient = new VoyClient({});
```

however I have the error

```
voy_search_bg.js:294 Uncaught (in promise) TypeError: wasm.voy_new is not a function
    at new Voy (voy_search_bg.js:294:1)
    at memoryTest (LLMs.js:114:1)
    at async callLLM (App.js:76:1)
```

**Comment by jacobhq** [comment]
I get this on the examples in the project too. I can't get any of them to work.
